[package]
name = "bevy_tailwind"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["macros"]

[dependencies]
bevy_tailwind_macro = { path = "macros" }

[dev-dependencies]
bevy = { version = "0.15.1", default-features = false, features = ["bevy_ui"] }
