[package]
name = "bevy_tailwind"
version = "0.1.0"
edition = "2024"
authors = ["notmd"]
repository = "https://github.com/notmd/bevy_tailwind"
description = "TailwindCSS for Bevy"
license = "MIT"
keywords = ["bevy", "tailwind", "css", "styled"]

[workspace]
members = ["macros", "macros/tests/*"]

[dependencies]
bevy_tailwind_macro = { path = "macros" }

[dev-dependencies]
bevy = { version = "0.15.1", default-features = false, features = [
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "bevy_text",
    "default_font",
] }
