name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

      - name: Format
        run: |
          cargo fmt --check
      - name: Check
        run: |
          cargo check --workspace --all-features
      - name: Test
        run: |
          cargo test --workspace --all-features
